stages:
  - install
  - test

# Install dependencies.
install:
  script:
    - npm ci
  artifacts:
    paths:
      - './node_modules'

# Runs tsc (TypeScript Compiler) on the web component source to check types.
test:tsc-tests:
  script: 
    - npm test
  needs:
    - install

# Run test build.
test:test-build
  script:
    - npm run build
  needs:
    - install
