stages:
  - build
  - test

# Builds dependencies, then builds the web components.
build:
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - './node_modules'
      - './build'

# Runs unit tests on the web component internals - like typechecking etc.
test:unit-tests:
  script: 
    - npm test
  needs:
    - build